### PR TITLE
ALU: use sub op directly, it's more optimized

### PR DESCRIPTION
**Pull request by gyurco**
Gives better timing results

### CODE REVIEW

**Comment by gyurco** [comment]
@TobiFlex can you check this?
The instruction tester didn't show any issues with the patch.

**Comment by TobiFlex** [comment]
@gyurco I cannot see any significant improvement. But I see a higher consumption of resources. approx. + 80LC's for the Cyclone II and approx + 30LC's for the Cyclone V. I don't like that.

**Comment by gyurco** [comment]
On what core did you try? I saw timing improvements on Minimig-AGA on MiST (Cyclone III).

**Comment by gyurco** [comment]
Re-tested, yeah slightly bigger with the patch. Actually not an important patch.

**Pull request closed without merging**
